### ISSUE TITLE
Stall/hang on KSP load

### ISSUE THREAD

**Issue by JoelleEmmily** [ChrisAdderley/NearFutureConstruction#11]
If either B9PartSwitch or NearFutureConstruction directory are deleted, game loads normally,

[KSP.log.txt](https://github.com/ChrisAdderley/NearFutureConstruction/files/291782/KSP.log.txt)
[Player.log.txt](https://github.com/ChrisAdderley/NearFutureConstruction/files/291784/Player.log.txt)
[buildID.txt](https://github.com/ChrisAdderley/NearFutureConstruction/files/291785/buildID.txt)

**Comment by ChrisAdderley** [comment]
You seem to be running KSP 1.1.0 (as shown by the first line in your logfile, in fact I think it's the prerelease?) instead of 1.1.2. Looks like that's causing ModuleManager to fail to load, and then of course NFC will fail to load its tank definitions, which are defined as MM patches. 

Upgrade your KSP to the latest version, then try again.

**Comment by JoelleEmmily** [comment]
Very sorry, you're absolutely correct. I still had Steam set to opt-in.
